AIX: Add missing FQDN() method for types.Host (#185)
Encountered this issue while building on AIX 7.3. This adds the
missing implementation.

```
# github.com/elastic/go-sysinfo/providers/aix
/go/pkg/mod/github.com/elastic/go-sysinfo@v1.11.0/providers/aix/host_aix_ppc64.go:57:9: cannot use newHost() (value of type *host) as types.Host value in return statement: *host does not implement types.Host (missing method FQDN)
```

---------

Co-authored-by: Ahmet SALIH <ahmet@binalyze.com>